### ISSUE TITLE
repo naming 관련 입니다.

### ISSUE THREAD

**Issue by dark1451** [the-pirates-corp/eslint-config#2]
https://www.notion.so/tpirates/Package-naming-convention-ccc442ff2c3a4ee19b10a866779ae373
규칙에 따라 library-node-codestyle, library-node-lint 등으로 하면 좋을것 같습니다! (+ 분리해도 좋을것 같아유)

이슈의 경우에는 당장 해결하자고 소통하는것이 아니고, 천천히 의견을 취합해 나가는것으로 참고 하면 좋을것 같아요! (ex 하루에 한번씩 체크/소통)

아싸 첫이슈!

**Comment by rrrrrrrrrrrocky** [comment]
@dark1451 개인적으로는 library-node-lint가 적절 할 듯 한데
(+ 분리해도 좋을것 같아유) <--- 이부분은 혹시 prettier와 eslint를 분리하자는 의견이 맞으실까요?

**Comment by dark1451** [comment]
> @dark1451 개인적으로는 library-node-lint가 적절 할 듯 한데 (+ 분리해도 좋을것 같아유) <--- 이부분은 혹시 prettier와 eslint를 분리하자는 의견이 맞으실까요?

네넵 ㅎㅎ 오전에 이야기 나눈것 처럼 mono-repo, npm package 분리 형태로 하면 좋을것 같네요!..
둘다 무조건 사용 하는걸로 세팅 할것 같긴한데.. 음..
의견 자유롭게 부탁합니다!

**Comment by rrrrrrrrrrrocky** [comment]
구두로 논의 된 library-node-code-convention으로 변경 후 이슈 닫도록하겠습니다!

**Comment by dark1451** [comment]
👍
